export enum TextFormat {
  // note: please don't judge me for the naming of these, they will not stay when we rework the UI
  DEFAULT_FONT_96PX,
  DEFAULT_FONT_96PX_BIG_SHADOW,
  DEFAULT_FONT_84PX_BIG_SHADOW,
  DEFAULT_FONT_80PX,
  DEFAULT_FONT_72PX,
  DEFAULT_FONT_72PX_MEDIUM_SHADOW,
  DEFAULT_FONT_64PX,
  DEFAULT_FONT_60PX,
  DEFAULT_FONT_56PX,
  DEFAULT_FONT_54PX,

  ALT_FONT_66PX,
  ALT_FONT_54PX,
  ALT_FONT_54PX_STROKE,
  ALT_FONT_44PX_STROKE,
}
