export enum TextStyle {
  MESSAGE,
  WINDOW,
  WINDOW_ALT,
  BATTLE_INFO,
  PARTY,
  PARTY_RED,
  SUMMARY,
  SUMMARY_ALT,
  SUMMARY_RED,
  SUMMARY_BLUE,
  SUMMARY_PINK,
  SUMMARY_GOLD,
  SUMMARY_GRAY,
  SUMMARY_GREEN,
  /** Money default styling (pale yellow) */
  MONEY,
  /** Money displayed in Windows (needs different colors based on theme) */
  MONEY_WINDOW,
  STATS_LABEL,
  STATS_VALUE,
  SETTINGS_VALUE,
  SETTINGS_LABEL,
  SETTINGS_SELECTED,
  SETTINGS_LOCKED,
  TOOLTIP_TITLE,
  TOOLTIP_CONTENT,
  MOVE_INFO_CONTENT,
  MOVE_PP_FULL,
  MOVE_PP_HALF_FULL,
  MOVE_PP_NEAR_EMPTY,
  MOVE_PP_EMPTY,
  SMALLER_WINDOW_ALT,
  BGM_BAR,
  PERFECT_IV,
  /** Default style for choices in ME */
  ME_OPTION_DEFAULT,
  /** Style for choices with special requirements in ME */
  ME_OPTION_SPECIAL,
  /** Style for challenge description */
  CHALLENGE_DESCRIPTION,
  GENDER_MALE,
  GENDER_FEMALE,
}
