import { PostDefendAbAttr } from "#abilities/post-defend-ab-attr";
import { AbAttrFlag } from "#enums/ab-attr-flag";
import { AbilityId } from "#enums/ability-id";
import { ElementalType } from "#enums/elemental-type";
import { MoveFlags } from "#enums/move-flags";
import { StatusEffect } from "#enums/status-effect";
import type { Pokemon } from "#field/pokemon";
import type { Move } from "#moves/move";

/**
 * Effect Spore's ability attribute
 *
 * When a Pokémon with this Ability is hit by a move that makes contact, there is a 9% chance of poison, 10% chance of paralysis, and 11% chance of sleep.
 * The total sum of these chances is 30%.
 */
export class EffectSporeAbAttr extends PostDefendAbAttr {
  public readonly chance = 30;
  private roll: number = Number.POSITIVE_INFINITY;

  constructor() {
    super();
    this._flags.add(AbAttrFlag.EFFECT_SPORE);
  }

  /**
   * Identical code to {@linkcode PostDefendContactApplyStatusEffectAbAttr}'s `applyPostDefend()` but it contains two conditional checks.
   * Effect Spore cannot affect the attacker if the attacker is Grass-type or has the ability Overcoat
   */
  public override apply(pokemon: Pokemon, simulated: boolean, attacker: Pokemon, _move: Move): void {
    const statusEffect = this.getStatus(this.roll);
    if (!simulated) {
      attacker.trySetStatus(statusEffect, true, pokemon);
    }
  }

  public override canApply(...[pokemon, , attacker, move]: Parameters<this["apply"]>): boolean {
    this.roll = pokemon.randSeedInt(100);
    return (
      this.roll < this.chance
      && !attacker.isOfType(ElementalType.GRASS, true, true)
      && !attacker.hasAbility(AbilityId.OVERCOAT)
      && move.checkFlag(MoveFlags.MAKES_CONTACT, attacker, pokemon)
      && !attacker.hasNonVolatileStatusEffect()
    );
  }

  /**
   * Returns a status effect based on the ability's roll
   * @param roll a number between 0 and 99 generated by randSeedInt
   * @returns a status effect that is either sleep, paralysis, or poison
   */
  private getStatus(roll: number): StatusEffect {
    const SLEEP_THRESHOLD = 11;
    const PARA_THRESHOLD = 10 + SLEEP_THRESHOLD;
    const PSN_THRESHOLD = 9 + PARA_THRESHOLD;
    if (roll < SLEEP_THRESHOLD) {
      return StatusEffect.SLEEP;
    }
    if (roll < PARA_THRESHOLD) {
      return StatusEffect.PARALYSIS;
    }
    if (roll < PSN_THRESHOLD) {
      return StatusEffect.POISON;
    }
    return StatusEffect.NONE;
  }
}
