import type { TrainerGender } from "#enums/trainer-gender";
import { TrainerSlot } from "#enums/trainer-slot";
import type { TrainerType } from "#enums/trainer-type";
import type { Pokemon } from "#field/pokemon";

/**
 * A record of generator functions mapped by {@linkcode TrainerGender}. When generating
 * a Trainer, the Trainer's name, title, sprite key, and other properties are determined
 * from the generator function under the desired {@linkcode TrainerGender}.
 * Generators defined under {@linkcode TrainerGender.DEFAULT} are considered the default
 * when a generator for the desired gender is undefined.
 */
type TrainerAssetGenerator<T = string> = Partial<Record<TrainerGender, () => T>>;
/** A function to generate a {@linkcode Pokemon} of a desired level */
type PartyPokemonGenerator = (level: number, trainerSlot: TrainerSlot) => Pokemon;

/**
 * Interface for the specification of a generated Trainer. Most properties
 * in this object are "generators" -- functions that return the desired data.
 * @see {@linkcode TrainerConfigBuilder}
 */
export interface NewTrainerConfig {
  /** The {@link TrainerType | type} of Trainer generated by this config */
  trainerType: TrainerType;
  /**
   * A set of generators for the Trainer's name.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   * The return value of each generator should be a localizable i18n key.
   */
  name: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's title.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   * The return value of each generator should be a localizable i18n key.
   */
  title: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's sprite key.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   */
  spriteKey: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's "close-up" sprite key, which may
   * be shown during the Trainer's dialogue.
   * This should either be empty (for no dialogue sprite) or contain one
   * generator for each supported {@linkcode TrainerGender}.
   */
  dialogueSpriteKey: TrainerAssetGenerator;
  /**
   * If `true`, the Trainer is considered a "boss". Boss Trainers have
   * modified AI command selection logic and may grant extra item rewards when
   * defeated.
   * @todo Item rewards for bosses are hard-coded outside of configs and should
   * be reorganized.
   */
  isBoss: boolean;
  /**
   * A generator to determine the background music to play during battle.
   * @todo How should BGM be handled for battles with multiple Trainer[Config]s?
   */
  battleBgm: () => string;
  /**
   * A generator to determine the background music to play during the Trainer's introduction.
   */
  encounterBgm: () => string;
  /**
   * A generator to determine the background music to play when the Trainer is defeated.
   * @todo Add default value
   */
  victoryBgm: () => string;
  /**
   * An array of generators for the Trainer's party Pokemon. When generated, the Pokemon
   * are added to {@linkcode globalScene} as enemies.
   */
  partyGenerators: PartyPokemonGenerator[];
  /**
   * A generator to determine the amount of money granted to the Player after defeating the Trainer
   * (relative to the base money amount)
   * @see {@linkcode MoneyRewardPhase}
   */
  moneyMultiplier: () => number;
}

/** A cache of {@linkcode NewTrainerConfig}s organized by {@linkcode TrainerType} */
export type TrainerConfigMap = Partial<Record<TrainerType, NewTrainerConfig>>;

/**
 * A cache of {@linkcode NewTrainerConfig}s organized by {@linkcode TrainerSlot}.
 * All slots except for {@linkcode TrainerSlot.NONE} must have a mapped config.
 */
type ConfigSlotMap = Record<Exclude<TrainerSlot, typeof TrainerSlot.NONE>, NewTrainerConfig>;

/**
 * Container for multiple {@linkcode NewTrainerConfig}s to be used in a singular battle.
 * This includes getters to resolve conflicting data/generators between the
 * included configs.
 */
export class CompoundTrainerConfig {
  public readonly configs: ConfigSlotMap;
  public readonly combinedTitle: string;

  constructor(configs: ConfigSlotMap, combinedTitle: string) {
    this.configs = configs;
    this.combinedTitle = combinedTitle;
  }

  public get isBoss(): boolean {
    const configValues = Object.values(this.configs).map((cfg) => cfg.isBoss);
    return configValues.includes(true);
  }

  public get battleBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].battleBgm;
  }

  public get encounterBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].encounterBgm;
  }

  public get victoryBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].victoryBgm;
  }

  // TODO: Should this use the maximum money multiplier or some other formula?
  public get moneyMultiplier(): () => number {
    return () => Math.max(...Object.values(this.configs).map((cfg) => cfg.moneyMultiplier()));
  }
}
