/* biome-ignore-start lint/correctness/noUnusedImports: tsdoc imports */
import type { PokemonSpecies } from "#data/pokemon-species";
import type { PokemonSpeciesForm } from "#data/pokemon-species-form";
/* biome-ignore-end lint/correctness/noUnusedImports: tsdoc imports */

import type { PartyMemberStrength } from "#enums/party-member-strength";
import type { SpeciesId } from "#enums/species-id";
import type { TrainerGender } from "#enums/trainer-gender";
import type { TrainerPoolTier } from "#enums/trainer-pool-tier";
import { type NonNullTrainerSlot, TrainerSlot } from "#enums/trainer-slot";
import type { TrainerType } from "#enums/trainer-type";
import type { EnemyPokemon, EnemyPokemonOptions } from "#field/enemy-pokemon";
import type { PokemonSpeciesFilter } from "#types/ui-types";
import type { CoercibleArray, NonEmptyArray } from "#types/utility-types";

/**
 * A record of generator functions mapped by {@linkcode TrainerGender}. When generating
 * a Trainer, the Trainer's name, title, sprite key, and other properties are determined
 * from the generator function under the desired {@linkcode TrainerGender}.
 * Generators defined under {@linkcode TrainerGender.DEFAULT} are considered the default
 * when a generator for the desired gender is undefined.
 */
type TrainerAssetGenerator<T = string> = Partial<Record<TrainerGender, () => T>>;

// #region TrainerConfig

export type TrainerAssetKey = "name" | "title" | "spriteKey" | "dialogueSpriteKey";

/**
 * Interface for the specification of a generated Trainer. Most properties
 * in this object are "generators" -- functions that return the desired data.
 * @see {@linkcode TrainerConfigBuilder}
 */
export interface NewTrainerConfig {
  /** The {@link TrainerType | type} of Trainer generated by this config */
  trainerType: TrainerType;
  /**
   * A set of generators for the Trainer's name.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   * The return value of each generator should be a localizable i18n key.
   */
  name: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's title.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   * The return value of each generator should be a localizable i18n key.
   */
  title: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's sprite key.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   */
  spriteKey: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's "close-up" sprite key, which may
   * be shown during the Trainer's dialogue.
   * This should either be empty (for no dialogue sprite) or contain one
   * generator for each supported {@linkcode TrainerGender}.
   */
  dialogueSpriteKey: TrainerAssetGenerator;
  /**
   * If `true`, the Trainer is considered a "boss". Boss Trainers have
   * modified AI command selection logic and may grant extra item rewards when
   * defeated.
   * @todo Item rewards for bosses are hard-coded outside of configs and should
   * be reorganized.
   */
  isBoss: boolean;
  /**
   * A generator to determine the background music to play during battle.
   * @todo How should BGM be handled for battles with multiple Trainer[Config]s?
   */
  battleBgm: () => string;
  /**
   * A generator to determine the background music to play during the Trainer's introduction.
   */
  encounterBgm: () => string;
  /**
   * A generator to determine the background music to play when the Trainer is defeated.
   * @todo Add default value
   */
  victoryBgm: () => string;
  /**
   * An array of configs for the Trainer's party Pokemon. When generated, the Pokemon
   * are added to {@linkcode globalScene} as enemies.
   */
  partyConfigs: TrainerPartyPokemonConfig[];
  /**
   * A fixed base seed offset component to be used when the Trainer's party is randomly generated.
   * If multiple configs have the same seed offset and apply the same RNG for species generation,
   * they will produce the same species of Pokemon.
   *
   * @privateRemarks
   * For organization purposes, it's best to supply this with a {@linkcode TrainerType} when needed,
   * but any number is valid.
   */
  partyBaseSeedOffset?: number;
  /**
   * A generator to determine the amount of money granted to the Player after defeating the Trainer
   * (relative to the base money amount)
   * @see {@linkcode MoneyRewardPhase}
   */
  moneyMultiplier: () => number;
}

// #endregion

/** A cache of {@linkcode NewTrainerConfig}s organized by {@linkcode TrainerType} */
export type TrainerConfigMap = Partial<Record<TrainerType, NewTrainerConfig>>;

/**
 * A cache of {@linkcode NewTrainerConfig}s organized by {@linkcode TrainerSlot}.
 * All slots except for {@linkcode TrainerSlot.NONE} must have a mapped config.
 */
export type TrainerSlotMap<T> = Record<NonNullTrainerSlot, T>;

// #region CompoundTrainerConfig
/**
 * Container for multiple {@linkcode NewTrainerConfig}s to be used in a singular battle.
 * This includes getters to resolve conflicting data/generators between the
 * included configs.
 */
export class CompoundTrainerConfig {
  public readonly configs: TrainerSlotMap<NewTrainerConfig>;
  public readonly combinedTitle: string;
  /**
   * If `true`, all Trainers' party Pokemon are generated using the same seed
   * offset. For example, if two party members' species are to be randomly selected
   * from an {@link PartyPokemonConfig.speciesPool | untiered species pool}, their
   * species will be of the same index within their respective pools.
   *
   * @privateRemarks
   * This is currently only used for the Twins, and is meant to give them matching
   * Pokemon pairs (e.g. Plusle + Minun).
   */
  public readonly useSameSeedForAllTrainers: boolean;

  constructor(
    configs: TrainerSlotMap<NewTrainerConfig>,
    combinedTitle: string,
    useSameSeedForAllTrainers: boolean = false,
  ) {
    this.configs = configs;
    this.combinedTitle = combinedTitle;
    this.useSameSeedForAllTrainers = useSameSeedForAllTrainers;
  }

  /**
   * @returns `true` if this Trainer combination is considered a boss battle.
   * @remarks
   * A Compound Trainer battle is considered a boss battle if at least one of the
   * Trainers involved {@link NewTrainerConfig.isBoss | is a boss}.
   */
  public get isBoss(): boolean {
    return Object.values(this.configs).some((cfg) => cfg.isBoss);
  }

  /**
   * The generator used to determine the BGM to play during battle.
   * @remarks
   * Compound Trainer battles always use the battle BGM of the Trainer in the first
   * slot ({@linkcode TrainerSlot.TRAINER}).
   */
  public get battleBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].battleBgm;
  }

  /**
   * The generator used to determine the BGM to play during the Trainers' introduction.
   * @remarks
   * Compound Trainer battles always use the encounter BGM of the Trainer in the first
   * slot ({@linkcode TrainerSlot.TRAINER}).
   */
  public get encounterBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].encounterBgm;
  }

  /**
   * The generator used to determine the BGM to play when the Trainer is defeated.
   * @remarks
   * Compound Trainer battles always use the victory BGM of the Trainer in the first
   * slot ({@linkcode TrainerSlot.TRAINER}).
   */
  public get victoryBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].victoryBgm;
  }

  // TODO: Should this use the maximum money multiplier or some other formula?
  public get moneyMultiplier(): () => number {
    return () => Math.max(...Object.values(this.configs).map((cfg) => cfg.moneyMultiplier()));
  }
}

// #endregion
// #region PartyPokemonConfig

/**
 * A list of Pokemon {@link SpeciesId | species} mapped by {@linkcode TrainerPoolTier}.
 * Not all tiers need to be included in the pool.
 * @example
 * ```
 * const validPool: TieredSpeciesPool = {
 *   [TrainerPoolTier.COMMON]: [SpeciesId.MAGIKARP, SpeciesId.FEEBAS],
 *   [TrainerPoolTier.UNCOMMON]: [SpeciesId.MUDKIP],
 *   // ...
 * };
 * ```
 */
export type TieredSpeciesPool = Partial<Record<TrainerPoolTier, SpeciesId[]>>;
/** Enemy Pokemon generation options that may be set for a Trainer's party Pokemon */
type ConfigurableEnemyPokemonOptions = Omit<
  EnemyPokemonOptions,
  | "id"
  | "trainerSlot"
  | "metLevel"
  | "metBiome"
  | "metSpecies"
  | "metWave"
  | "evoCounter"
  | "usedTMs"
  | "pauseEvolutions"
  | "stellarTypesBoosted"
>;

/**
 * Interface for the specification of one or more Pokemon within a Trainer's party
 */
export interface TrainerPartyPokemonConfig extends ConfigurableEnemyPokemonOptions {
  /**
   * A tiered pool of {@link SpeciesId | species} from which the Pokemon is generated.
   * The lower a species' tier, the more likely it will be selected for generation.
   *
   * If this and {@linkcode speciesPool} are both defined in a config, this pool takes priority
   */
  tieredSpeciesPool?: TieredSpeciesPool;
  /**
   * An untiered pool of {@link SpeciesId | species} from which the Pokemon is generated.
   * Each species in this pool has an equal chance of being selected for generation.
   */
  speciesPool?: NonEmptyArray<SpeciesId>;
  /**
   * A condition function to filter certain {@link SpeciesId | species} of Pokemon
   * from being generated. If defined, a species must meet the condition to
   * be selected for generation.
   *
   * If {@linkcode tieredSpeciesPool} or {@linkcode speciesPool} are also defined,
   * this filter is applied onto the given pool. Otherwise, this filter is
   * applied to all Pokemon that {@link PokemonSpeciesForm.canSpawnAsRandomSpecies | can spawn randomly}.
   */
  speciesFilter?: PokemonSpeciesFilter;
  /**
   * If `false`, restricts Pokemon of species that have already been
   * generated in the Trainer's party (if possible)
   */
  allowDuplicates: boolean;
  /**
   * If `false`, restricts {@link PokemonSpecies.isLegendLike | legend-like}
   * Pokemon from being generated.
   */
  allowLegendaries: boolean;
  /**
   * The {@link PartyMemberStrength | strength} of the generated Pokemon.
   * Used to determine the Pokemon's level for the current wave.
   * If set to an array, its length should be equal to {@linkcode count}.
   */
  strength: CoercibleArray<PartyMemberStrength>;
  /**
   * (Optional) A set of functions to apply variable {@link PartyMemberStrength | strength}
   * to generated Pokemon. If defined, this takes precedent over the config's
   * {@linkcode strength} property. If set to an array, its length should be
   * equal to {@linkcode count}.
   */
  variableStrength?: CoercibleArray<() => PartyMemberStrength>;
  /** The number of Pokemon to generate from this config */
  count: number;
  /**
   * If `false`, the generated Pokemon's species may be adjusted to a stage
   * in its evolution line that is appropriate for its level. If `true`, this
   * adjustment step is skipped.
   */
  ignoreEvolution: boolean;
  /**
   * (Optional) A condition for this config to apply when the Trainer's party is
   * generated. If this condition isn't met, this config is ignored.
   */
  condition?: () => boolean;
  /**
   * (Optional) A callback function to change the properties of the generated
   * Pokemon after it is constructed.
   */
  postProcess?: (pokemon: EnemyPokemon) => void;
}
