import { globalScene } from "#app/global-scene";
import type { PokemonSpecies } from "#data/pokemon-species";
import type { SpeciesId } from "#enums/species-id";
import { TrainerGender } from "#enums/trainer-gender";
import { TrainerSlot } from "#enums/trainer-slot";
import type { TrainerType } from "#enums/trainer-type";
import type { EnemyPokemon } from "#field/enemy-pokemon";
import type { Pokemon } from "#field/pokemon";
import type { PokemonSpeciesFilter } from "#types/ui-types";
import { getPokemonSpecies } from "#utils/pokemon-utils";
import { randSeedItem } from "#utils/random-utils";

/**
 * A record of generator functions mapped by {@linkcode TrainerGender}. When generating
 * a Trainer, the Trainer's name, title, sprite key, and other properties are determined
 * from the generator function under the desired {@linkcode TrainerGender}.
 * Generators defined under {@linkcode TrainerGender.DEFAULT} are considered the default
 * when a generator for the desired gender is undefined.
 */
type TrainerAssetGenerator<T = string> = Partial<Record<TrainerGender, () => T>>;
/** A function to generate a {@linkcode Pokemon} of a desired level */
type PartyPokemonGenerator = (level: number) => Pokemon;

/**
 * Interface for the specification of a generated Trainer. Most properties
 * in this object are "generators" -- functions that return the desired data.
 * @see {@linkcode TrainerConfigBuilder}
 */
export interface NewTrainerConfig {
  /** The {@link TrainerType | type} of Trainer generated by this config */
  trainerType: TrainerType;
  /**
   * A set of generators for the Trainer's name.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   * The return value of each generator should be a localizable i18n key.
   */
  name: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's title.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   * The return value of each generator should be a localizable i18n key.
   */
  title: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's sprite key.
   * This should contain one generator for each supported {@linkcode TrainerGender}.
   */
  spriteKey: TrainerAssetGenerator;
  /**
   * A set of generators for the Trainer's "close-up" sprite key, which may
   * be shown during the Trainer's dialogue.
   * This should either be empty (for no dialogue sprite) or contain one
   * generator for each supported {@linkcode TrainerGender}.
   */
  dialogueSpriteKey: TrainerAssetGenerator;
  /**
   * If `true`, the Trainer is considered a "boss". Boss Trainers have
   * modified AI command selection logic and may grant extra item rewards when
   * defeated.
   * @todo Item rewards for bosses are hard-coded outside of configs and should
   * be reorganized.
   */
  isBoss: boolean;
  /**
   * A generator to determine the background music to play during battle.
   * @todo How should BGM be handled for battles with multiple Trainer[Config]s?
   */
  battleBgm: () => string;
  /**
   * A generator to determine the background music to play during the Trainer's introduction.
   */
  encounterBgm: () => string;
  /**
   * A generator to determine the background music to play when the Trainer is defeated.
   * @todo Add default value
   */
  victoryBgm: () => string;
  /**
   * An array of generators for the Trainer's party Pokemon. When generated, the Pokemon
   * are added to {@linkcode globalScene} as enemies.
   */
  partyGenerators: PartyPokemonGenerator[];
  /**
   * A generator to determine the amount of money granted to the Player after defeating the Trainer
   * (relative to the base money amount)
   * @see {@linkcode MoneyRewardPhase}
   */
  moneyMultiplier: () => number;
}

/** A cache of {@linkcode NewTrainerConfig}s organized by {@linkcode TrainerType} */
export type TrainerConfigMap = Partial<Record<TrainerType, NewTrainerConfig>>;

/**
 * A cache of {@linkcode NewTrainerConfig}s organized by {@linkcode TrainerSlot}.
 * All slots except for {@linkcode TrainerSlot.NONE} must have a mapped config.
 */
type ConfigSlotMap = Record<Exclude<TrainerSlot, typeof TrainerSlot.NONE>, NewTrainerConfig>;

/**
 * Container for multiple {@linkcode NewTrainerConfig}s to be used in a singular battle.
 * This includes getters to resolve conflicting data/generators between the
 * included configs.
 */
export class CompoundTrainerConfig {
  public readonly configs: ConfigSlotMap;
  public readonly combinedTitle: string;

  constructor(configs: ConfigSlotMap, combinedTitle: string) {
    this.configs = configs;
    this.combinedTitle = combinedTitle;
  }

  public get isBoss(): boolean {
    const configValues = Object.values(this.configs).map((cfg) => cfg.isBoss);
    return configValues.includes(true);
  }

  public get battleBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].battleBgm;
  }

  public get encounterBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].encounterBgm;
  }

  public get victoryBgm(): () => string {
    return this.configs[TrainerSlot.TRAINER].victoryBgm;
  }

  // TODO: Should this use the maximum money multiplier or some other formula?
  public get moneyMultiplier(): () => number {
    return () => Math.max(...Object.values(this.configs).map((cfg) => cfg.moneyMultiplier()));
  }
}

/**
 * Builder class for constructing a {@linkcode NewTrainerConfig} for Trainer generation.
 * This includes a chaining API to initialize the config's generators and a
 * validator to ensure all required generators are properly initialized in runtime.
 */
export class TrainerConfigBuilder {
  /**
   * The internal {@linkcode NewTrainerConfig} constructed by this builder
   */
  private readonly config: Partial<NewTrainerConfig> = {
    name: {},
    title: {},
    spriteKey: {},
    dialogueSpriteKey: {},
    isBoss: false,
    partyGenerators: [],
    moneyMultiplier: () => 1,
  };

  /**
   * The {@linkcode TrainerGender | TrainerGenders} supported by this builder. This is populated
   * within API calls to initialize gender-mapped properties (e.g. {@linkcode name}).
   * When the builder is {@link validate | validated}, it ensures that
   * each gender-mapped property has defined generators for all supported genders.
   */
  private readonly possibleGenders: Set<TrainerGender> = new Set<TrainerGender>();

  /**
   * Determines if all required properties to build a {@linkcode NewTrainerConfig}
   * have been properly initialized. This also ensures
   * that each {@link possibleGenders | supported gender} has a valid generator
   * under each required property.
   *
   * @privateRemarks
   * `config` is supplied instead of using `this.config` directly so that
   * the type guard may apply.
   */
  private validate(config: Partial<NewTrainerConfig>): config is NewTrainerConfig {
    if (config.trainerType == null) {
      console.error("trainerType is not defined!");
      return false;
    }

    if (this.possibleGenders.size === 0) {
      console.error(
        "No supported genders detected. This may happen if the config's name, title, and/or sprite key(s) are not initialized.",
      );
      return false;
    }

    const requiredGenderMappedGeneratorKeys = ["name", "title", "spriteKey"] as const;
    for (const gender of this.possibleGenders) {
      if (gender === TrainerGender.DEFAULT) {
        continue;
      }

      for (const k of requiredGenderMappedGeneratorKeys) {
        // We know `config[k]` is defined based on default values
        if (config[k]![gender] == null && config[k]![TrainerGender.DEFAULT] == null) {
          console.error(`${k} does not have a matching generator for supported gender ${gender}!`);
          return false;
        }
      }

      // This should be defined based on default values
      const dialogueSpriteKey = config.dialogueSpriteKey!;
      if (
        Object.keys(dialogueSpriteKey).length > 0
        && dialogueSpriteKey[gender] == null
        && dialogueSpriteKey[TrainerGender.DEFAULT] == null
      ) {
        console.error(`dialogueSpriteKey has a defined generator, but not for supported gender ${gender}!`);
        return false;
      }
    }

    if (config.partyGenerators!.length === 0) {
      console.error("partyGenerators is empty!");
      return false;
    }

    return true;
  }

  /** Constructs a {@linkcode NewTrainerConfig} from the builder's properties and returns it */
  public build(): NewTrainerConfig {
    if (!this.validate(this.config)) {
      throw new Error(`Required fields missing in generated config: ${this.config}`);
    }
    return this.config;
  }

  /**
   * Sets a {@linkcode TrainerType} for Trainers generated from this config.
   * @param trainerType - The {@linkcode TrainerType} to set
   * @returns `this`
   */
  public withTrainerType(trainerType: TrainerType): this {
    this.config.trainerType = trainerType;
    return this;
  }

  /**
   * Sets a singular name for the Trainer under the specified {@linkcode TrainerGender}.
   * @param name - The name to set. Should be a localizable `i18n` key
   * @param gender - The {@linkcode TrainerGender} under which the name is assigned
   * @returns `this`
   */
  public withFixedName(name: string, gender: TrainerGender = TrainerGender.DEFAULT): this {
    this.possibleGenders.add(gender);
    this.config.name![gender] = () => name;
    return this;
  }

  /**
   * Sets a random name for the Trainer out of the given name pool
   * and under the specified {@linkcode Gender}.
   * @param names - A set of possible names. Each name should be a localizable `i18n` key.
   * @param gender - The {@linkcode TrainerGender} under which the name is assigned
   * @returns `this`
   */
  public withNameFromPool(names: string[], gender: TrainerGender = TrainerGender.DEFAULT): this {
    this.possibleGenders.add(gender);
    this.config.name![gender] = () => randSeedItem(names);
    return this;
  }

  /**
   * Sets a title for the Trainer under the specified {@linkcode TrainerGender}.
   * @param title - The title to set. Should be a localizable `i18n` key
   * @param gender - The {@linkcode TrainerGender} under which the title is assigned
   * @returns `this`
   */
  public withTitle(title: string, gender: TrainerGender = TrainerGender.DEFAULT): this {
    this.possibleGenders.add(gender);
    this.config.title![gender] = () => title;
    return this;
  }

  /**
   * Sets a sprite key for the Trainer under the specified {@linkcode TrainerGender}.
   * @param spriteKey - The sprite key to set.
   * @param gender - The {@linkcode TrainerGender} under which the sprite key is assigned
   * @returns `this`
   */
  public withSpriteKey(spriteKey: string, gender: TrainerGender = TrainerGender.DEFAULT): this {
    this.possibleGenders.add(gender);
    this.config.spriteKey![gender] = () => spriteKey;
    return this;
  }

  /**
   * Sets a sprite key for the Trainer's "close-up" image to show during the
   * Trainer's dialogue.
   * @param spriteKey - The sprite key to set
   * @param gender - The {@linkcode TrainerGender} under which the sprite key is assigned
   * @returns `this`
   */
  public withDialogueSpriteKey(spriteKey: string, gender: TrainerGender = TrainerGender.DEFAULT): this {
    this.possibleGenders.add(gender);
    this.config.dialogueSpriteKey![gender] = () => spriteKey;
    return this;
  }

  /**
   * Sets the background music to play when battling the Trainer.
   * @param bgm - The background music to set
   * @returns `this`
   */
  public withBattleBgm(bgm: string): this {
    this.config.battleBgm = () => bgm;
    return this;
  }

  /**
   * Sets the background music to play during the Trainer's introduction dialogue.
   * @param bgm - The background music to set
   * @returns `this`
   */
  public withEncounterBgm(bgm: string): this {
    this.config.encounterBgm = () => bgm;
    return this;
  }

  /**
   * Sets the background music to play when the Trainer is defeated.
   * @param bgm - The background music to set
   * @returns `this`
   */
  public withVictoryBgm(bgm: string): this {
    this.config.victoryBgm = () => bgm;
    return this;
  }

  /**
   * Appends a Pokemon of a set species to the Trainer's party.
   * @param species - The {@linkcode SpeciesId} of the added Pokemon
   * @param trainerSlot - (Default `TRAINER`) The {@linkcode TrainerSlot} to which the Pokemon belongs
   * @param ignoreEvolution - (Default `false`) If `true`, the generated Pokemon's final species will be identical to
   * `species` regardless of the Pokemon's level. Otherwise, the Pokemon's final species is set to
   * a stage in its evolution line that is appropriate for its level.
   * @param postProcess - (Optional) A callback that may be used to apply custom characteristics
   * to the Pokemon after it has been generated.
   * @todo Remove or refactor {@linkcode TrainerSlot} so that the extra param isn't needed
   */
  public withPokemon(
    species: SpeciesId,
    trainerSlot: TrainerSlot = TrainerSlot.TRAINER,
    ignoreEvolution: boolean = false,
    postProcess?: (pokemon: EnemyPokemon) => void,
  ): this {
    return this.withPokemonFromPool([species], trainerSlot, ignoreEvolution, postProcess);
  }

  /**
   * Appends a Pokemon from a pool of species to the Trainer's party.
   * @param speciesPool - The set of {@linkcode SpeciesId} from which the Pokemon is generated.
   * When generated, the Pokemon will be of a random species from this pool
   * @param trainerSlot - (Default `TRAINER`) The {@linkcode TrainerSlot} to which the Pokemon belongs
   * @param ignoreEvolution - (Default `false`) If `true`, the generated Pokemon's final species will be identical to
   * `species` regardless of the Pokemon's level. Otherwise, the Pokemon's final species is set to
   * a stage in its evolution line that is appropriate for its level.
   * @param postProcess - (Optional) A callback that may be used to apply custom characteristics
   * to the Pokemon after it has been generated.
   * @todo Remove or refactor {@linkcode TrainerSlot} so that the extra param isn't needed
   */
  public withPokemonFromPool(
    speciesPool: readonly SpeciesId[],
    trainerSlot: TrainerSlot = TrainerSlot.TRAINER,
    ignoreEvolution: boolean = false,
    postProcess?: (pokemon: EnemyPokemon) => void,
  ): this {
    this.config.partyGenerators!.push((level: number) => {
      let species = randSeedItem([...speciesPool]);
      if (!ignoreEvolution) {
        species = getPokemonSpecies(species).getEnemySpeciesForLevel(level, true);
      }

      return globalScene.addEnemyPokemon(
        getPokemonSpecies(species),
        level,
        trainerSlot,
        undefined,
        false,
        undefined,
        postProcess,
      );
    });

    return this;
  }

  /**
   * Appends a Pokemon of a {@link globalScene.randomSpecies | random species} that satisfies conditions
   * from the given filter and other parameters.
   */
  public withPokemonFromFilter(
    filter: PokemonSpeciesFilter,
    trainerSlot: TrainerSlot = TrainerSlot.TRAINER,
    allowLegendaries: boolean = false,
    postProcess?: (pokemon: EnemyPokemon) => void,
  ): this {
    const speciesFilter = (species: PokemonSpecies): boolean => {
      return (allowLegendaries || !species.isLegendLike()) && !species.isTrainerForbidden() && filter(species);
    };

    this.config.partyGenerators!.push((level: number) => {
      const waveIndex = globalScene.currentBattle.waveIndex;
      const species = getPokemonSpecies(
        globalScene.randomSpecies(waveIndex, level, false, speciesFilter).getEnemySpeciesForLevel(level, true),
      );

      return globalScene.addEnemyPokemon(species, level, trainerSlot, undefined, false, undefined, postProcess);
    });

    return this;
  }

  /**
   * Sets a fixed multiplier for the money reward for defeating the Trainer.
   * @param multiplier - The multiplier to set
   * @returns `this`
   */
  public withMoneyMultiplier(multiplier: number): this {
    this.config.moneyMultiplier = () => multiplier;
    return this;
  }

  /**
   * Sets the config to use the Rival character's assets
   * (i.e. name, title, sprite keys, and bgm).
   * @returns `this`
   */
  public withRivalAssets(): this {
    return this.withFixedName("finn", TrainerGender.MALE)
      .withFixedName("ivy", TrainerGender.FEMALE)
      .withTitle("rival")
      .withEncounterBgm("rival")
      .withBattleBgm("battle_rival");
  }
}
