name: Deploy Tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    if: github.repository == 'despair-games/poketernity'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build:dev
        env:
          NODE_ENV: development

      - name: Set up SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.BETA_SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          echo "${{ secrets.BETA_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/*
          ssh-keyscan -H ${{ secrets.BETA_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy build on server
        run: |
          ssh ${{ secrets.BETA_SSH_USER }}@${{ secrets.BETA_SSH_HOST }} "mkdir -p ${{ secrets.BETA_DESTINATION_DIR }}/poketernity/${{ env.TAG_NAME }}/"
          rsync --del --no-times --checksum -vrm dist/* ${{ secrets.BETA_SSH_USER }}@${{ secrets.BETA_SSH_HOST }}:${{ secrets.BETA_DESTINATION_DIR }}/poketernity/${{ env.TAG_NAME }}/
