name: "Lint"

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta
  merge_group:
    types: [checks_requested]

jobs:
  run-linters:
    name: Run all linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Node modules
        run: pnpm i
      
      # Lint files with Biome-Lint - https://biomejs.dev/linter/
      - name: Run Biome-Lint
        run: pnpm biome-ci
        id: biome_lint
        continue-on-error: true
      
      # Validate dependencies with dependency-cruiser - https://github.com/sverweij/dependency-cruiser
      - name: Run Dependency-Cruise
        run: pnpm depcruise
        id: depcruise
        continue-on-error: true

      # Validate types with tsc - https://www.typescriptlang.org/docs/handbook/compiler-options.html#using-the-cli
      - name: Run Typecheck
        run: pnpm typecheck
        id: typecheck
        continue-on-error: true
      
      - name: Evaluate for Errors
        env:
          BIOME_LINT_OUTCOME: ${{ steps.biome_lint.outcome }}
          DEPCRUISE_OUTCOME: ${{ steps.depcruise.outcome }}
          TYPECHECK_OUTCOME: ${{ steps.typecheck.outcome }}
        run: |
          # Check for Errors

          RED='\033[0;31m'
          GREEN='\033[0;32m'
          NC='\033[0m' # No Color

          print_result() {
            local name=$1
            local outcome=$2
            if [ "$outcome" == "success" ]; then
              echo -e "${GREEN}✅ $name: $outcome${NC}"
            else
              echo -e "${RED}❌ $name: $outcome${NC}"
            fi
          }

          print_result "Biome" "$BIOME_LINT_OUTCOME"
          print_result "Depcruise" "$DEPCRUISE_OUTCOME"
          print_result "Typecheck" "$TYPECHECK_OUTCOME"

          if [[ "$BIOME_LINT_OUTCOME" != "success" || \
                "$DEPCRUISE_OUTCOME" != "success" || \
                "$TYPECHECK_OUTCOME" != "success" ]]; then
            echo -e "\n${RED}❌ One or more checks failed.${NC}"
            exit 1
          fi

          echo -e "\n${GREEN}✅ All checks passed.${NC}"
