name: Test Template

on:
  workflow_call:
    inputs:
      shard:
        description: The numerical index of the current shard; must be no greater than totalShards.
        required: true
        type: number
      totalShards:
        description: The total number of shards to split tests into; should be the same across shards.
        required: true
        type: number

jobs:
  test:
    name: Shard ${{ inputs.shard }} of ${{ inputs.totalShards }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
        with:
          submodules: "recursive"

      - uses: $/.github/actions/setup-deps

      - name: Run tests
        run: pnpm test:silent --shard=${{ inputs.shard }}/${{ inputs.totalShards }}
