import { globalScene } from "#app/global-scene";
import { getTrainerDialogue, type TrainerMessageType } from "#data/dialogue";
import { type NonDefaultTrainerGender, TrainerGender } from "#enums/trainer-gender";
import { type NonNullTrainerSlot, TrainerSlot } from "#enums/trainer-slot";
import type { TrainerType } from "#enums/trainer-type";
import type { EnemyPokemon } from "#field/enemy-pokemon";
import type { ModifierTypeFunc } from "#modifier/modifier-type";
import type { TrainerSaveDataSet } from "#system/trainer-save-data";
import { TrainerAi } from "#trainers/trainer-ai";
import type {
  CompositeTrainerConfig,
  RequireOneTrainer,
  TrainerAssetKey,
  TrainerConfig,
  TrainerPartyPokemonConfig,
  TrainerSlotMap,
} from "#trainers/trainer-config";
import { coerceArray } from "#utils/common-utils";
import { getPokemonSpecies } from "#utils/pokemon-utils";
import { randSeedInt, randSeedItem } from "#utils/random-utils";
import { getPartyMemberSeedOffset, getPartyPokemonLevel, getPartyPokemonSpecies } from "#utils/trainer-utils";
import i18next from "i18next";

// #region TrainerData

/**
 * Class for storing all data for a specific Trainer instance as derived from a
 * {@linkcode TrainerConfig}. When created, the Trainer's party of {@linkcode EnemyPokemon}
 * is also generated and added to {@linkcode globalScene}.
 */
export class TrainerData {
  /** The {@linkcode TrainerSlot} this Trainer occupies */
  public readonly trainerSlot: NonNullTrainerSlot;
  /** The Trainer's {@linkcode TrainerType} */
  public readonly trainerType: TrainerType;
  /**
   * The localizable key for the Trainer's name
   * @see {@linkcode getLocalizedName}
   */
  public readonly name: string;
  /**
   * The localizable key for the Trainer's title
   * @see {@linkcode getLocalizedName}
   */
  public readonly title: string;
  /** The key under which the Trainer's sprite is stored */
  public readonly spriteKey: string;
  /**
   * (Optional) The key under which the Trainer's dialogue sprite is stored.
   * If defined, the specified sprite will display as an overlay during the Trainer's dialogue.
   */
  public readonly dialogueSpriteKey?: string;
  /**
   * Whether this Trainer is classified as a boss. Boss Trainers offer more item rewards to the
   * Player when defeated.
   */
  public readonly isBoss: boolean;
  /** The bgm key/path to play while the Player battles this Trainer */
  public readonly battleBgm: string;
  /** (Optional) The bgm key/path to play during this Trainer's opening dialogue */
  public readonly encounterBgm?: string;
  /** The bgm key/path to play when the Player defeats this Trainer */
  public readonly victoryBgm: string;
  /**
   * `true` if this Trainer acts as the *only* Trainer in a double battle, allowing for
   * two of their Pokemon to be active at once.
   */
  public readonly double: boolean;
  /**
   * The Trainer's party of {@linkcode EnemyPokemon}.
   * When initialized, this is also injected into {@linkcode globalScene.currentBattle}
   */
  public readonly party: EnemyPokemon[];
  /** A multiplier for the money granted to the Player upon defeating this Trainer. */
  public readonly moneyMultiplier: number;
  public readonly modifierRewards: ModifierTypeFunc[];
  /** The Trainer's {@linkcode TrainerGender} */
  public readonly gender: NonDefaultTrainerGender;
  /**
   * The {@linkcode TrainerAi} defining the Trainer's behavior when selecting
   * Pokemon turn commands, switch/summon actions, and Terastallization
   */
  public readonly ai: TrainerAi;

  /**
   * @param trainerSlot - The {@linkcode TrainerSlot} to which the Trainer belongs.
   * This must not be {@linkcode TrainerSlot.NONE}.
   * @param config - The {@linkcode TrainerConfig} from which the data is generated
   * @param gender - (Optional) The Trainer's {@linkcode TrainerGender}. If not defined,
   * the Trainer's gender is {@link initGender | determined randomly}.
   * @param partySizeLimit - (Optional) A limit to the number of Pokemon that may
   * be generated by this Trainer's party configs
   * @param useSameSeedForAllTrainers - (Default `false`) If `true`, other
   * Trainers in the same battle will use the same seed offset for global RNG
   * calls (assuming they also have this set to `true` for their construction)
   */
  constructor(
    trainerSlot: NonNullTrainerSlot,
    config: TrainerConfig,
    gender?: NonDefaultTrainerGender,
    useSameSeedForAllTrainers: boolean = false,
    partySizeLimit?: number,
  ) {
    this.trainerSlot = trainerSlot;
    this.trainerType = config.trainerType;
    this.gender = gender ?? this.initGender(config);
    this.name = this.getGenderedAsset(config, "name")!;
    this.title = this.getGenderedAsset(config, "title")!;
    this.spriteKey = this.getGenderedAsset(config, "spriteKey")!;
    this.dialogueSpriteKey = this.getGenderedAsset(config, "dialogueSpriteKey");
    this.isBoss = config.isBoss;
    this.battleBgm = config.battleBgm();
    this.encounterBgm = config.encounterBgm?.();
    this.victoryBgm = config.victoryBgm();
    this.ai = new TrainerAi(this, config.aiType, config.teraMode);
    this.double = config.isDouble(); // TODO: this could also factor in overrides...
    this.party = this.generateParty(trainerSlot, config, useSameSeedForAllTrainers, partySizeLimit);
    this.moneyMultiplier = config.moneyMultiplier();
    this.modifierRewards = config.modifierRewards;
  }

  /**
   * Obtains the Trainer's localized name in the format
   * `"{{title}} {{name}}"`
   * @param withTitle - (Default `true`) If `true`, also includes the Trainer's
   * title
   * @returns The localized name
   */
  public getLocalizedName(withTitle: boolean = true) {
    const title = withTitle ? `${i18next.t(`trainerClasses:${this.title}`)} ` : "";
    const name = i18next.t(`trainerNames:${this.name}`);
    return title + name;
  }

  /**
   * Fetches a random message from the Trainer's dialogue pool for the given message type.
   * The message selection is seeded by wave index.
   * @param messageType - The type of message to fetch, e.g. `"encounter"`
   * @returns A random message from the given message pool, or `undefined` if the Trainer
   * does not have a populated message pool under the given type.
   */
  public getDialogue(messageType: TrainerMessageType): string | undefined {
    let dialogue: string | undefined;
    globalScene.executeWithSeedOffset(() => {
      dialogue = getTrainerDialogue(messageType, this.trainerType, this.gender);
    }, globalScene.currentBattle.waveIndex);

    return dialogue;
  }

  /**
   * Resolves the Trainer's gender which determines the pools from which the
   * Trainer's name, title, and sprite keys are extracted. The Trainer's gender
   * is determined randomly, and the chance of resolving to a specific gender is
   * proportional to the number of entries in the given config's name pool for
   * that gender, compared to other genders.
   * @param config - The {@linkcode TrainerConfig} used to generate the Trainer.
   * @returns The Trainer's {@linkcode TrainerGender}.
   */
  private initGender(config: TrainerConfig): NonDefaultTrainerGender {
    const supportedGenders = Object.keys(config.name).map((k) => Number(k) as NonDefaultTrainerGender);

    const genderWeights = supportedGenders.map((g) => config.name[g]!.length);
    let roll = randSeedInt(genderWeights.reduce((total, w) => total + w));
    for (let i = 0; i < supportedGenders.length; i++) {
      if (roll < genderWeights[i]) {
        return supportedGenders[i];
      }
      roll -= genderWeights[i];
    }
    return supportedGenders[0];
  }

  /**
   * @param config - The {@linkcode TrainerConfig} used to generate the asset
   * @param key - The type of asset to generate
   * @returns The asset (i18n key or path) generated corresponding to this Trainer's gender,
   * or `undefined` if no asset can be generated under the given parameters.
   * @privateRemarks {@linkcode gender} should be initialized before calling this method.
   */
  private getGenderedAsset(config: TrainerConfig, key: TrainerAssetKey): string | undefined {
    const assetGenerator = config[key]?.[this.gender] ?? config[key]?.[TrainerGender.DEFAULT];
    if (key !== "dialogueSpriteKey" && assetGenerator == null) {
      throw new Error(`trainer-data: Cannot find asset for ${key} (gender=${this.gender})`);
    }

    return assetGenerator?.();
  }

  /**
   * Generates the Trainer's party of {@linkcode EnemyPokemon} from the given config
   * and adds them to {@linkcode globalScene}.
   * @param trainerSlot - The {@linkcode TrainerSlot} this Trainer occupies
   * @param config - The {@linkcode TrainerConfig} used to generate this Trainer.
   * This method only uses the {@linkcode partyConfigs} and {@linkcode partyBaseSeedOffset} properties.
   * @param useSameSeedForAllTrainers - If `true`, RNG during Pokemon generation
   * will disregard {@linkcode trainerSlot} in its seed offset, allowing Trainers
   * in multiple slots to use the same seed.
   * @param partySizeLimit - (Optional) If set to `N`, only the last `N` valid Pokemon
   * specified by the Trainer's party config(s) will be generated.
   * @returns An array of {@linkcode EnemyPokemon} representing the Trainer's
   * party in slot order.
   * @see {@linkcode getPartyPokemonLevel}
   * @see {@linkcode getPartyPokemonSpecies}
   */
  private generateParty(
    trainerSlot: NonNullTrainerSlot,
    { partyConfigs, partyBaseSeedOffset, useSameSeedForAllPokemon }: TrainerConfig,
    useSameSeedForAllTrainers: boolean,
    partySizeLimit?: number,
  ): EnemyPokemon[] {
    const party: EnemyPokemon[] = [];
    const scaledWaveIndex = globalScene.gameMode.getWaveForDifficulty(globalScene.currentBattle.waveIndex);

    /**
     * The party configs to be used for party generation. Configs are selected
     * based on the following:
     * - Any config whose {@linkcode TrainerPartyPokemonConfig.condition | condition} is not met is removed.
     * - If multiple valid configs are available under a single slot, one of the
     * configs is selected at random.
     */
    const finalPartyConfigs = partyConfigs
      .map((cfgs) => cfgs.filter((c) => c.condition == null || c.condition()))
      .filter((cfgs) => cfgs.length > 0)
      .map((cfgs) => randSeedItem(cfgs));

    let remainingPokemon = partySizeLimit ?? 6;

    for (const config of finalPartyConfigs.toReversed()) {
      const finalCfg = config.aiType
        ? config
        : {
            ...config,
            aiType: this.ai.aiType,
          };

      for (let i = 0; i < finalCfg.count; i++) {
        if (remainingPokemon <= 0) {
          return party;
        }
        remainingPokemon--;

        const levelFuncs = coerceArray(finalCfg.levelFunc);
        const seedOffset = getPartyMemberSeedOffset(
          trainerSlot,
          party.length,
          partyBaseSeedOffset,
          useSameSeedForAllPokemon,
          useSameSeedForAllTrainers,
        );
        globalScene.executeWithSeedOffset(() => {
          const level = (levelFuncs[i] ?? levelFuncs.at(-1))(scaledWaveIndex);
          const species = getPokemonSpecies(getPartyPokemonSpecies(level, party, finalCfg));
          party.unshift(globalScene.addEnemyPokemon(species, level, finalCfg, finalCfg.postProcess));
        }, seedOffset);
      }
    }

    if (party.length === 0) {
      throw new Error("No valid party members generated!");
    }
    return party;
  }
}

// #endregion
// #region CompoundTrainerData

export class CompoundTrainerData {
  public readonly trainerData: TrainerSlotMap<TrainerData>;
  public readonly title: string;

  /**
   * @param config - The {@linkcode CompositeTrainerConfig} from which the data is generated
   * @param genders - The {@linkcode TrainerGender}s of each Trainer, organized by {@linkcode TrainerSlot}.
   * If a gender isn't specified for a slot, that slot's Trainer will be given a
   * random gender (see {@linkcode TrainerData.initGender}).
   */
  constructor(config: CompositeTrainerConfig, genders: Partial<TrainerSlotMap<NonDefaultTrainerGender>> = {}) {
    for (const [slot, cfg] of Object.entries(config.configs)) {
      const trainerSlot = Number(slot) as NonNullTrainerSlot;
      this.trainerData[slot] = new TrainerData(
        trainerSlot,
        cfg,
        genders[trainerSlot],
        config.useSameSeedForAllTrainers,
        3, // Party size is limited to 3 per Trainer
      );
    }
    this.title = config.combinedTitle;
  }
}

// #endregion
// #region TrainerDataSet

type FromConfigParameters = ConstructorParameters<typeof TrainerData> extends [TrainerSlot, ...infer P] ? P : never;

/**
 * A container for the {@linkcode TrainerData} of all Trainers involved in a battle.
 * Includes getters to resolve conflicting data between multiple Trainers.
 */
export class TrainerDataSet {
  /** The {@linkcode TrainerData} of all involved Trainers, organized by {@linkcode TrainerSlot} */
  public readonly trainers: RequireOneTrainer<TrainerData>;
  /** The title of the Trainer set, to be displayed at the start of the battle */
  public readonly title: string;

  /**
   * Builds a {@linkcode TrainerDataSet} from a single Trainer's {@linkcode TrainerConfig}.
   * This is a shorthand for constructing a {@linkcode TrainerData} instance, then
   * building a `TrainerDataSet` from that instance.
   *
   * This method's parameters mirror those of the {@linkcode TrainerData} constructor.
   * @returns The constructed {@linkcode TrainerDataSet}
   */
  public static fromConfig(...params: FromConfigParameters): TrainerDataSet {
    return new TrainerDataSet(new TrainerData(TrainerSlot.TRAINER, ...params));
  }

  /**
   * Builds a {@linkcode TrainerDataSet} from a {@linkcode CompositeTrainerConfig} (for multi-Trainer battles).
   * This is a shorthand for constructing a {@linkcode CompoundTrainerData} instance,
   * then building a `TrainerDataSet` from that instance.
   *
   * This method's parameters mirror those of the {@linkcode CompoundTrainerData} constructor.
   * @returns The constructed {@linkcode TrainerDataSet}
   */
  public static fromCompositeConfig(...params: ConstructorParameters<typeof CompoundTrainerData>): TrainerDataSet {
    return new TrainerDataSet(new CompoundTrainerData(...params));
  }

  constructor(source: TrainerData | CompoundTrainerData | TrainerSaveDataSet) {
    if (source instanceof TrainerData) {
      this.trainers = { [TrainerSlot.TRAINER]: source };
    } else if (source instanceof CompoundTrainerData) {
      this.trainers = source.trainerData;
    } else {
      // TODO: Is this typesafe?
      this.trainers = Object.fromEntries(
        Object.entries(source.trainerSaveData).map(([key, saveData]) => [key, saveData.toTrainerData()]),
      ) as RequireOneTrainer<TrainerData>;
    }

    this.title = source.title;
  }

  /**
   * Obtains a localized name for the Trainer set. If this is a Trainer pair, each
   * Trainer's individual title is omitted in favor of the combined title.
   * @param withTitle - (Default `true`) If `true`, includes the Trainer set's {@linkcode TrainerDataSet.title | title}
   * @returns The localized name(s) (and title if specified)
   * @see {@linkcode TrainerData.getLocalizedName}
   */
  public getLocalizedName(withTitle: boolean = true) {
    let title = "";
    if (withTitle) {
      title = this.title.includes(":") ? `${i18next.t(this.title)} ` : `${i18next.t(`trainerClasses:${this.title}`)} `;
    }
    const names = Object.values(this.trainers).map((td) => td.getLocalizedName(false));

    if (names.length === 2) {
      return (
        title
        + i18next.t("trainerNames:joinNames", {
          name1: names[0],
          name2: names[1],
        })
      );
    }

    return title + names[0];
  }

  /** Whether or not this set is to be used for a double battle */
  public get double(): boolean {
    return this.trainers[TrainerSlot.TRAINER].double || Object.values(this.trainers).length === 2;
  }

  /**
   * @returns `true` if this Trainer combination is considered a boss battle.
   * @remarks
   * Multi-Trainer battles are considered boss battles if at least one of the
   * Trainers involved {@link TrainerConfig.isBoss | is a boss}.
   */
  public get isBoss(): boolean {
    return Object.values(this.trainers).some((td) => td.isBoss);
  }

  /**
   * The BGM to play during the Trainers' introduction dialogue. Multi-Trainer
   * battles use the first defined encounter BGM override in slot order (if any exist).
   */
  public get encounterBgm(): string | undefined {
    return Object.values(this.trainers).find((td) => td.encounterBgm != null)?.encounterBgm;
  }

  /**
   * The BGM to play during battle. Multi-Trainer battles always use the battle
   * BGM of the Trainer in the first slot ({@linkcode TrainerSlot.TRAINER}).
   */
  public get battleBgm(): string {
    return this.trainers[TrainerSlot.TRAINER].battleBgm;
  }

  /**
   * The BGM to play when the Trainer(s) are defeated. Multi-Trainer battles always use
   * the victory BGM of the Trainer in the first slot ({@linkcode TrainerSlot.TRAINER}).
   */
  public get victoryBgm(): string {
    return this.trainers[TrainerSlot.TRAINER].victoryBgm;
  }

  /**
   * The money reward multiplier for defeating all Trainers in this battle.
   * @todo Should this use the maximum money multiplier among all Trainers (current) or some other formula?
   */
  public get moneyMultiplier(): number {
    return Math.max(...Object.values(this.trainers).map((td) => td.moneyMultiplier));
  }

  /** A map of each included Trainer's {@linkcode EnemyPokemon} organized by {@linkcode TrainerSlot}. */
  public get party(): RequireOneTrainer<EnemyPokemon[]> {
    return Object.fromEntries(
      Object.entries(this.trainers).map(([key, tData]) => [key, tData.party]),
    ) as RequireOneTrainer<EnemyPokemon[]>;
  }

  /**
   * The combined party of all {@linkcode EnemyPokemon} involved in the Trainer battle.
   * @remarks
   * This should be injected into {@linkcode globalScene.currentBattle.enemyParty}
   * once all Pokemon are fully generated for the Trainer battle.
   * @todo Finalize this data structure. We may need to restrict individual
   * Trainers' parties to length (6 / number of involved Trainers) and/or
   * fill empty party slots with `undefined`
   */
  public get combinedParty(): EnemyPokemon[] {
    return Object.values(this.trainers).flatMap((td) => td.party);
  }

  /**
   * The {@linkcode ModifierTypeFunc}s to generate item rewards for defeating
   * all Trainers in this battle.
   */
  public get modifierRewards(): ModifierTypeFunc[] {
    const rewards: ModifierTypeFunc[] = [];
    for (const trainer of Object.values(this.trainers)) {
      rewards.push(...trainer.modifierRewards);
    }
    return rewards;
  }

  public getDialogueQueue(messageType: TrainerMessageType): [NonNullTrainerSlot, string][] {
    const messages: [NonNullTrainerSlot, string][] = [];
    for (const [slot, td] of Object.entries(this.trainers)) {
      const message = td.getDialogue(messageType);
      if (message) {
        messages.push([Number(slot) as NonNullTrainerSlot, message]);
      }
    }
    return messages;
  }
}
